[package]
name = "esp32-playground"
version = "0.1.0"
authors = ["Fang-Pen Lin <hello@fangpenlin.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.77"

[[bin]]
name = "esp32-playground"
harness = false # do not use the built in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = []

[dependencies]
esp-idf-sys = "0.36.0"

[build-dependencies]
embuild = { version = "0.33", features = ["glob", "kconfig", "cmake", "espidf"] }

[package.metadata.esp-idf-sys]
esp_idf_version = "v5.2.2"

[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "espressif/esp_tinyusb", version = "1.5.0" }

[patch.crates-io]
embuild = { git = "https://github.com/esp-rs/embuild" }
esp-idf-sys = { git = "https://github.com/esp-rs/esp-idf-sys" }
